name: Build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get the source code    
      uses: actions/checkout@v1
    - name: install dependencies
      run: npm ci
    - name: Build
      run: npm run all